name: OrangeHRM Database image test suite

on:
    push:
      branches: [ mariadb-10.2 ]

env:
    REGISTRY: hub.docker.com
    IMAGE_REPO_NAME: "orangehrm/orangehrm-db-images"
    TEST_TAG_NAME: "mariadb-10.2"
    MYSQL_PASSWORD: "1234"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Verify prerequisits
              run: |
                docker --version
                docker-compose --version
                composer --version

            - name: Build docker image
              run: docker build -t ${{ env.IMAGE_REPO_NAME }}:${{ env.TEST_TAG_NAME }} docker-image

            - name: Spin up a container
              run: |
                docker run -itd --name db_container -e MYSQL_ROOT_PASSWORD=${{ env.MYSQL_PASSWORD }} ${{ env.IMAGE_REPO_NAME }}:${{ env.TEST_TAG_NAME }}
                docker ps -a
            
            - name: Install test dependencis
              run: composer install
                          
            - name: Run unit tests
              run: php vendor/bin/codecept run unit
            
            - name: last not always
              run: echo "hello world chanaka"
            
            - name: always task
              if: always()
              run: |
                echo "This is hello world always ${{ job.status }}"
                echo ${GITHUB_REF#refs/heads/}
                echo ${GITHUB_REPOSITORY}