name: OrangeHRM Database image test suite

on:
    push:
      branches: [ mariadb-10.2 ]   
    pull_request:
      branches: [ mariadb-10.2 ]

env:
    REGISTRY: hub.docker.com
    DOCKER_HUB_REPO: "orangehrm/orangehrm-db-images"
    DEFAULT_IMAGE_TAG: "latest"
    MYSQL_PASSWORD: "1234"
    UPSTREAM_REPO: "orangehrm/orangehrm-db-images"
    UPSTREAM_BRANCH: "refs/heads/mariadb-10.2"

jobs:
    Build:
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Verify prerequisits
              run: |
                docker --version
                docker-compose --version
                composer --version
                cat /etc/os/release
            
            - name: Install test dependencis
              run: composer install
                          
            - name: Build docker image
              run: docker build -t ${{ env.DOCKER_HUB_REPO }}:${{ env.DEFAULT_IMAGE_TAG }} docker-image

            - name: Spin up a container
              run: |
                docker run -itd --name db_container -e MYSQL_ROOT_PASSWORD=${{ env.MYSQL_PASSWORD }} ${{ env.DOCKER_HUB_REPO }}:${{ env.DEFAULT_IMAGE_TAG }}
                docker ps -a

            - name: Run unit tests
              run: php vendor/bin/codecept run unit  
              
            - name: login to docker hub
              if: ${{ env.GITHUB_REPOSITORY == env.UPSTREAM_REPO && env.GITHUB_REF == env.UPSTREAM_BRANCH && job.status="success" }}
              run: echo "loggin in"
            
            - name: push docker image
              if: ${{ env.GITHUB_REPOSITORY == env.UPSTREAM_REPO && env.GITHUB_REF == env.UPSTREAM_BRANCH && job.status="success" }}
              run: echo "pushing image"
            
            - name: log out from docker hub
              if: ${{ env.GITHUB_REPOSITORY == env.UPSTREAM_REPO && env.GITHUB_REF == env.UPSTREAM_BRANCH }}
              run: echo "log out"

