name: OrangeHRM Database image test suite

on:
    push:
      branches: [ mariadb-10.2 ]   
    pull_request:
      branches: [ mariadb-10.2 ]

env:
    REGISTRY: hub.docker.com
    DOCKER_HUB_REPO: "orangehrm/orangehrm-db-images"
    DEFAULT_TAG_NAME: "latest"
    MYSQL_PASSWORD: "1234"
    UPSTREAM_REPO: "orangehrm/orangehrm-db-images"
    UPSTREAM_BRANCH: "refs/heads/mariadb-10.2"

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Verify prerequisits
              run: |
                docker --version
                docker-compose --version
                composer --version
            
            - name: Install test dependencis
              run: composer install
                          
            - name: Build docker image
              run: docker build -t ${{ env.DOCKER_HUB_REPO }}:${{ env.DEFAULT_TAG_NAME }} docker-image

            - name: Spin up a container
              run: |
                docker run -itd --name db_container -e MYSQL_ROOT_PASSWORD=${{ env.MYSQL_PASSWORD }} ${{ env.DOCKER_HUB_REPO }}:${{ env.DEFAULT_TAG_NAME }}
                docker ps -a

            - name: Run unit tests
              run: |
                sleep 10s
                php vendor/bin/codecept run unit  
              
            - name: Get installed mariadb version
              run: |
                echo "VERSION_TAG_NAME=$(docker exec db_container yum list installed MariaDB-Server | grep MariaDB-server | awk '{print $2}' | cut -d'-' -f 1)" >> $GITHUB_ENV

            - name: New image with a version tag
              run: |
                echo $VERSION_TAG_NAME
                echo '${{ env.VERSION_TAG_NAME }}'
                docker tag ${{ env.DOCKER_HUB_REPO }}:${{ env.DEFAULT_TAG_NAME }} ${{ env.DOCKER_HUB_REPO }}:${{ env.VERSION_TAG_NAME }} 

            - name: sample verification
              run: |
                docker images
                echo $VERSION_TAG_NAME

            - name: push docker image
              if: ${{ env.GITHUB_REPOSITORY == env.UPSTREAM_REPO && env.GITHUB_REF == env.UPSTREAM_BRANCH}}
              run: |
                echo "loggin in"
                echo "pushing both images"
                echo "log out"
            


